apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: keycloak
spec:
  selector:
    app: fastapi-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort
