# IMPORTANT: Do NOT commit a real token to git.
# Apply this secret manually:
#   kubectl create secret generic github-token \
#     --namespace argocd \
#     --from-literal=token=<YOUR_GITHUB_PAT>
#
# The token needs: repo (read), pull_request (read) permissions
# so ArgoCD can poll GitHub for open PRs with the 'preview' label.
#
# This file is a template only (base64-encoded placeholder).
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  token: REPLACE_WITH_REAL_TOKEN
