apiVersion: v1
kind: Service
metadata:
  name: keycloak-nodeport
  namespace: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 31111
      name: https
