apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: keycloak
spec:
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
